/* Generated By:JavaCC: Do not edit this line. AsmetaLParserTokenManager.java */
package de.ovgu.cide.fstgen.parsers.generated_AsmetaL;
import java.io.*;
import java.util.*;
import cide.gast.*;
import cide.gparser.*;
import de.ovgu.cide.fstgen.ast.*;
import cide.gparser.*;
public class AsmetaLParserTokenManager implements AsmetaLParserConstants
{
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1, long active2)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0xbe703fdfc036e000L) != 0L || (active1 & 0x5e8006aebefdL) != 0L)
         {
            jjmatchedKind = 123;
            return 38;
         }
         if ((active0 & 0x140L) != 0L || (active1 & 0x2000000000L) != 0L)
            return 2;
         if ((active0 & 0xfc0003f800000L) != 0L)
         {
            jjmatchedKind = 118;
            return 70;
         }
         if ((active0 & 0x180000000490000L) != 0L || (active1 & 0x210008110000L) != 0L)
            return 17;
         if ((active0 & 0x4000002000000000L) != 0L || (active1 & 0x1004000L) != 0L)
         {
            jjmatchedKind = 123;
            return 26;
         }
         if ((active1 & 0x100L) != 0L)
         {
            jjmatchedKind = 123;
            return 11;
         }
         if ((active1 & 0x400002L) != 0L)
         {
            jjmatchedKind = 123;
            return 35;
         }
         if ((active1 & 0xc00000000L) != 0L || (active2 & 0x200L) != 0L)
            return 73;
         return -1;
      case 1:
         if ((active0 & 0xfc00000000000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 118;
               jjmatchedPos = 1;
            }
            return 72;
         }
         if ((active0 & 0x100L) != 0L)
            return 0;
         if ((active0 & 0x100010000000000L) != 0L || (active1 & 0x90000018000L) != 0L)
            return 38;
         if ((active0 & 0xfe703effc037e000L) != 0L || (active1 & 0x768007fe7fffL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 123;
               jjmatchedPos = 1;
            }
            return 38;
         }
         if ((active0 & 0x3f800000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 117;
               jjmatchedPos = 1;
            }
            return 74;
         }
         if ((active0 & 0x480000L) != 0L || (active1 & 0x8000000L) != 0L)
            return 16;
         return -1;
      case 2:
         if ((active0 & 0x8000006000L) != 0L || (active1 & 0x578000841002L) != 0L)
            return 38;
         if ((active0 & 0x9400000000000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 118;
               jjmatchedPos = 2;
            }
            return 72;
         }
         if ((active0 & 0x3f800000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 117;
               jjmatchedPos = 2;
            }
            return 74;
         }
         if ((active0 & 0x6800000000000L) != 0L)
            return 72;
         if ((active0 & 0xfe703f7fc03f8000L) != 0L || (active1 & 0x2000077b6ffdL) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 123;
               jjmatchedPos = 2;
            }
            return 38;
         }
         if ((active0 & 0x400000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 123;
               jjmatchedPos = 2;
            }
            return 14;
         }
         return -1;
      case 3:
         if ((active0 & 0x3e800000L) != 0L)
         {
            jjmatchedKind = 117;
            jjmatchedPos = 3;
            return 74;
         }
         if ((active0 & 0xb8602f7f8077c000L) != 0L || (active1 & 0x2080077b665dL) != 0L)
         {
            jjmatchedKind = 123;
            jjmatchedPos = 3;
            return 38;
         }
         if ((active0 & 0x4610100040080000L) != 0L || (active1 & 0x9a0L) != 0L)
            return 38;
         if ((active0 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 118;
            jjmatchedPos = 3;
            return 72;
         }
         if ((active0 & 0x8400000000000L) != 0L)
            return 72;
         if ((active0 & 0x1000000L) != 0L)
            return 74;
         return -1;
      case 4:
         if ((active0 & 0x860040000200000L) != 0L || (active1 & 0x8007400608L) != 0L)
            return 38;
         if ((active0 & 0xb0002b7f8057c000L) != 0L || (active1 & 0x2000003b6055L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 123;
               jjmatchedPos = 4;
            }
            return 38;
         }
         if ((active0 & 0x20000000L) != 0L)
            return 74;
         if ((active0 & 0x1e800000L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 117;
               jjmatchedPos = 4;
            }
            return 74;
         }
         if ((active0 & 0x1000000000000L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 118;
               jjmatchedPos = 4;
            }
            return 72;
         }
         return -1;
      case 5:
         if ((active0 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 118;
            jjmatchedPos = 5;
            return 72;
         }
         if ((active0 & 0x100001420003c000L) != 0L || (active1 & 0xb6054L) != 0L)
            return 38;
         if ((active0 & 0x1e800000L) != 0L)
         {
            jjmatchedKind = 117;
            jjmatchedPos = 5;
            return 74;
         }
         if ((active0 & 0xa0002a3d80540000L) != 0L || (active1 & 0x200004300001L) != 0L)
         {
            jjmatchedKind = 123;
            jjmatchedPos = 5;
            return 38;
         }
         return -1;
      case 6:
         if ((active0 & 0x18000000L) != 0L)
         {
            jjmatchedKind = 117;
            jjmatchedPos = 6;
            return 74;
         }
         if ((active0 & 0xc00100000L) != 0L || (active1 & 0x200000100001L) != 0L)
            return 38;
         if ((active0 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 118;
            jjmatchedPos = 6;
            return 72;
         }
         if ((active0 & 0x6800000L) != 0L)
            return 74;
         if ((active0 & 0xa0002a3180440000L) != 0L || (active1 & 0x4200000L) != 0L)
         {
            jjmatchedKind = 123;
            jjmatchedPos = 6;
            return 38;
         }
         return -1;
      case 7:
         if ((active0 & 0x280100000000L) != 0L || (active1 & 0x4000000L) != 0L)
            return 38;
         if ((active0 & 0xa000023080440000L) != 0L || (active1 & 0x200000L) != 0L)
         {
            jjmatchedKind = 123;
            jjmatchedPos = 7;
            return 38;
         }
         if ((active0 & 0x1000000000000L) != 0L)
            return 72;
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 117;
            jjmatchedPos = 7;
            return 74;
         }
         if ((active0 & 0x8000000L) != 0L)
            return 74;
         return -1;
      case 8:
         if ((active0 & 0xa000021000440000L) != 0L)
            return 38;
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 117;
            jjmatchedPos = 8;
            return 74;
         }
         if ((active0 & 0x2080000000L) != 0L || (active1 & 0x200000L) != 0L)
         {
            jjmatchedKind = 123;
            jjmatchedPos = 8;
            return 38;
         }
         return -1;
      case 9:
         if ((active0 & 0x2000000000L) != 0L || (active1 & 0x200000L) != 0L)
            return 38;
         if ((active0 & 0x10000000L) != 0L)
            return 74;
         if ((active0 & 0x80000000L) != 0L)
         {
            jjmatchedKind = 123;
            jjmatchedPos = 9;
            return 38;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1, long active2)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1, active2), pos + 1);
}
private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private final int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 9:
         return jjStopAtPos(0, 2);
      case 10:
         return jjStopAtPos(0, 3);
      case 12:
         return jjStopAtPos(0, 5);
      case 13:
         return jjStopAtPos(0, 4);
      case 32:
         return jjStopAtPos(0, 1);
      case 33:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200000000L, 0x0L);
      case 35:
         return jjStopAtPos(0, 144);
      case 40:
         return jjStopAtPos(0, 130);
      case 41:
         return jjStopAtPos(0, 132);
      case 42:
         return jjStopAtPos(0, 100);
      case 43:
         return jjStartNfaWithStates_0(0, 98, 73);
      case 44:
         return jjStopAtPos(0, 131);
      case 45:
         jjmatchedKind = 99;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x200L);
      case 46:
         jjmatchedKind = 138;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x800L);
      case 47:
         jjmatchedKind = 101;
         return jjMoveStringLiteralDfa1_0(0x140L, 0x0L, 0x0L);
      case 58:
         jjmatchedKind = 133;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x20000L);
      case 60:
         jjmatchedKind = 93;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x40000000L, 0x44000L);
      case 61:
         return jjStopAtPos(0, 92);
      case 62:
         jjmatchedKind = 95;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100000000L, 0x8000L);
      case 64:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800000000000L, 0x0L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x2000000000000L, 0x0L, 0x0L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x10800000L, 0x0L, 0x0L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x8000000L, 0x0L, 0x0L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x20000000L, 0x0L, 0x0L);
      case 74:
         return jjMoveStringLiteralDfa1_0(0x4000000L, 0x0L, 0x0L);
      case 76:
         return jjMoveStringLiteralDfa1_0(0x2000000L, 0x0L, 0x0L);
      case 77:
         return jjMoveStringLiteralDfa1_0(0x4000000000000L, 0x0L, 0x0L);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x1000000L, 0x0L, 0x0L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x1400000000000L, 0x0L, 0x0L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x8000000000000L, 0x0L, 0x0L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x800000000000L, 0x0L, 0x0L);
      case 91:
         return jjStopAtPos(0, 140);
      case 93:
         return jjStopAtPos(0, 141);
      case 94:
         return jjStopAtPos(0, 102);
      case 97:
         return jjMoveStringLiteralDfa1_0(0xa000020a000L, 0x20000000000L, 0x0L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x40000000000L, 0x0L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x4000002000000000L, 0x1004000L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x10c80100000L, 0x8000L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x2c00100000020000L, 0x2a200dL, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x20000100000000L, 0x40L, 0x0L);
      case 105:
         jjmatchedKind = 55;
         return jjMoveStringLiteralDfa1_0(0x100000000490000L, 0x210008110000L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400002L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x1000004000L, 0x400000000a00L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x48000000000L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x8000008040000000L, 0x80000000000L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x1000204200040000L, 0x40080L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x210000000000000L, 0x800400L, 0x0L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x40000000000000L, 0x10L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x6000020L, 0x0L);
      case 120:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100000000000L, 0x0L);
      case 123:
         return jjStopAtPos(0, 134);
      case 124:
         return jjStopAtPos(0, 135);
      case 125:
         return jjStopAtPos(0, 136);
      default :
         return jjMoveNfa_0(3, 0);
   }
}
private final int jjMoveStringLiteralDfa1_0(long active0, long active1, long active2)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1, active2);
      return 1;
   }
   switch(curChar)
   {
      case 42:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(1, 8, 0);
         break;
      case 45:
         if ((active2 & 0x40000L) != 0L)
            return jjStopAtPos(1, 146);
         break;
      case 46:
         if ((active2 & 0x800L) != 0L)
            return jjStopAtPos(1, 139);
         break;
      case 47:
         if ((active0 & 0x40L) != 0L)
            return jjStopAtPos(1, 6);
         break;
      case 60:
         if ((active2 & 0x4000L) != 0L)
            return jjStopAtPos(1, 142);
         break;
      case 61:
         if ((active1 & 0x40000000L) != 0L)
            return jjStopAtPos(1, 94);
         else if ((active1 & 0x100000000L) != 0L)
            return jjStopAtPos(1, 96);
         else if ((active1 & 0x200000000L) != 0L)
            return jjStopAtPos(1, 97);
         else if ((active2 & 0x20000L) != 0L)
            return jjStopAtPos(1, 145);
         break;
      case 62:
         if ((active2 & 0x200L) != 0L)
            return jjStopAtPos(1, 137);
         else if ((active2 & 0x8000L) != 0L)
            return jjStopAtPos(1, 143);
         break;
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x9000000L, active1, 0L, active2, 0L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L, active1, 0L, active2, 0L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000L, active1, 0L, active2, 0L);
      case 84:
         return jjMoveStringLiteralDfa2_0(active0, 0x2800000L, active1, 0L, active2, 0L);
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000L, active1, 0L, active2, 0L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x4026040000000000L, active1, 0x1001a00L, active2, 0L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000000L, active1, 0L, active2, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x800880100000L, active1, 0x40002L, active2, 0L);
      case 102:
         if ((active0 & 0x100000000000000L) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x10000010000L, active2, 0L);
      case 103:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000L, active1, 0L, active2, 0L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x200004000000000L, active1, 0x6004000L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000L, active1, 0x20L, active2, 0L);
      case 107:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x80L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000000000000L, active1, 0L, active2, 0L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000L, active1, 0x200000000000L, active2, 0L);
      case 110:
         if ((active1 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 91;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x2840120000480000L, active1, 0x20000282015L, active2, 0L);
      case 111:
         if ((active1 & 0x8000L) != 0L)
         {
            jjmatchedKind = 79;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x1013000004000L, active1, 0xd48000400040L, active2, 0L);
      case 114:
         if ((active1 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 107, 38);
         return jjMoveStringLiteralDfa2_0(active0, 0x10400000000000L, active1, 0x800000L, active2, 0L);
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0xa000L, active1, 0L, active2, 0L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000200000000L, active1, 0x100000L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x8208100000000L, active1, 0x500L, active2, 0L);
      case 118:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L, active1, 0L, active2, 0L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000000000L, active1, 0L, active2, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000L, active1, 0x20008L, active2, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000000L, active1, 0L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1, active2);
}
private final int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(0, old0, old1, old2); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1, 0L);
      return 2;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000L, active1, 0L);
      case 76:
         return jjMoveStringLiteralDfa3_0(active0, 0x2800000L, active1, 0L);
      case 77:
         return jjMoveStringLiteralDfa3_0(active0, 0x11000000L, active1, 0L);
      case 83:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L, active1, 0L);
      case 86:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x4200000000L, active1, 0L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x400200L);
      case 100:
         if ((active1 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 105, 38);
         else if ((active1 & 0x400000000000L) != 0L)
         {
            jjmatchedKind = 110;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x2840000000004000L, active1, 0x282005L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000040200000L, active1, 0x100000L);
      case 102:
         if ((active1 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 104, 38);
         return jjMoveStringLiteralDfa3_0(active0, 0x80100000L, active1, 0L);
      case 103:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 49, 72);
         return jjMoveStringLiteralDfa3_0(active0, 0x40000L, active1, 0L);
      case 104:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000080000L, active1, 0x6000898L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x28000000000000L, active1, 0x100L);
      case 109:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(2, 13, 38);
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x3500000000L, active1, 0x10000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000000L, active1, 0x4000L);
      case 112:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 50, 72);
         return jjMoveStringLiteralDfa3_0(active0, 0x30000L, active1, 0x200000000000L);
      case 113:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 47, 72);
         else if ((active1 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(2, 82, 38);
         break;
      case 114:
         if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(2, 76, 38);
         else if ((active1 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 108, 38);
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000L, active1, 0x800000000440L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x44000c0000000000L, active1, 0L);
      case 116:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 39, 38);
         else if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(2, 65, 38);
         else if ((active1 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 106;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x8001020020L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x10100000000000L, active1, 0L);
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000L, active1, 0L);
      case 119:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000000L, active1, 0L);
      case 121:
         if ((active1 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(2, 87, 38);
         return jjMoveStringLiteralDfa3_0(active0, 0x20000008000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1, 0L);
}
private final int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1, 0L);
      return 3;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000L, active1, 0L);
      case 69:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(3, 24, 74);
         break;
      case 80:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000L, active1, 0L);
      case 82:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000L, active1, 0L);
      case 83:
         return jjMoveStringLiteralDfa4_0(active0, 0x2800000L, active1, 0L);
      case 84:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x10400500000L, active1, 0x400040L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x400L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000L, active1, 0x1000001L);
      case 100:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 46, 72);
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000L, active1, 0L);
      case 101:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 51, 72);
         else if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 52, 38);
         else if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 58, 38);
         else if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 62, 38);
         else if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 72, 38);
         return jjMoveStringLiteralDfa4_0(active0, 0x8041000000000000L, active1, 0x20000L);
      case 104:
         if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(3, 69, 38);
         break;
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x800041880000000L, active1, 0x808000200000L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x200006000004L);
      case 109:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 44, 38);
         break;
      case 110:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 57, 38);
         else if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(3, 75, 38);
         return jjMoveStringLiteralDfa4_0(active0, 0x248000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x30000L, active1, 0x14000L);
      case 112:
         if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(3, 71, 38);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x2000L);
      case 113:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x10L);
      case 114:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(3, 30, 38);
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000L, active1, 0x100200L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x2020200000000000L, active1, 0x80008L);
      case 116:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(3, 19, 38);
         return jjMoveStringLiteralDfa4_0(active0, 0x1000082200000000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1, 0L);
}
private final int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1, 0L);
      return 4;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000L, active1, 0L);
      case 73:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000L, active1, 0L);
      case 78:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000L, active1, 0L);
      case 80:
         return jjMoveStringLiteralDfa5_0(active0, 0x2800000L, active1, 0L);
      case 82:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(4, 29, 74);
         break;
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000L, active1, 0x102001L);
      case 99:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 42, 38);
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000008000L, active1, 0L);
      case 101:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 53, 38);
         else if ((active1 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 89;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x204000000000L, active1, 0x4080004L);
      case 102:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 54, 38);
         else if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 59, 38);
         break;
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x800000000000L);
      case 104:
         if ((active1 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(4, 88, 38);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x10200000000L, active1, 0x200000000000L);
      case 108:
         if ((active1 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(4, 86, 38);
         return jjMoveStringLiteralDfa5_0(active0, 0x4000L, active1, 0x40L);
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000L, active1, 0L);
      case 110:
         if ((active1 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 103, 38);
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000L, active1, 0x30000L);
      case 111:
         if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(4, 73, 38);
         else if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(4, 74, 38);
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x8001082000430000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x4000L);
      case 116:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(4, 21, 38);
         else if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(4, 67, 38);
         return jjMoveStringLiteralDfa5_0(active0, 0x1100000000L, active1, 0x200000L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000L, active1, 0x10L);
      case 118:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000000L, active1, 0L);
      case 119:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1, 0L);
}
private final int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000L, active1, 0L);
      case 69:
         return jjMoveStringLiteralDfa6_0(active0, 0xa800000L, active1, 0L);
      case 83:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000000000L, active1, 0L);
      case 99:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(5, 33, 38);
         break;
      case 100:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 38, 38);
         else if ((active1 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(5, 81, 38);
         break;
      case 101:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(5, 14, 38);
         else if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(5, 68, 38);
         else if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(5, 78, 38);
         else if ((active1 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(5, 80, 38);
         return jjMoveStringLiteralDfa6_0(active0, 0x800000000L, active1, 0x200000200000L);
      case 104:
         if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 60, 38);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000580400000L, active1, 0x800000000000L);
      case 108:
         if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(5, 70, 38);
         return jjMoveStringLiteralDfa6_0(active0, 0x100000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000000L, active1, 0L);
      case 110:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 40, 38);
         break;
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x3000000000L, active1, 0L);
      case 113:
         if ((active1 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(5, 83, 38);
         break;
      case 114:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(5, 15, 38);
         else if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(5, 77, 38);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x4000000L);
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000000000L, active1, 0x1L);
      case 116:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(5, 16, 38);
         else if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(5, 17, 38);
         else if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(5, 66, 38);
         return jjMoveStringLiteralDfa6_0(active0, 0x200000040000L, active1, 0x100000L);
      case 119:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1, 0L);
}
private final int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 67:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(6, 23, 74);
         else if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(6, 25, 74);
         break;
      case 69:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(6, 26, 74);
         break;
      case 83:
         return jjMoveStringLiteralDfa7_0(active0, 0x18000000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000400000L, active1, 0L);
      case 99:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(6, 34, 38);
         return jjMoveStringLiteralDfa7_0(active0, 0x80000000000L, active1, 0L);
      case 100:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(6, 35, 38);
         break;
      case 101:
         if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(6, 64, 38);
         else if ((active1 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(6, 84, 38);
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000000L, active1, 0x4000000L);
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000000000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x800000000000L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x200100000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000L, active1, 0x200000L);
      case 115:
         if ((active1 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 109, 38);
         break;
      case 116:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(6, 20, 38);
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000080000000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x40000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1, 0L);
}
private final int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000L, active1, 0L);
      case 83:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(7, 27, 74);
         break;
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x800000200000L);
      case 99:
         if ((active1 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(7, 90, 38);
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000000000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000000000L, active1, 0L);
      case 102:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 45, 38);
         break;
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x20080000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000000L, active1, 0L);
      case 110:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(7, 32, 38);
         return jjMoveStringLiteralDfa8_0(active0, 0x400000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000000000000L, active1, 0L);
      case 116:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 43, 38);
         else if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 48, 72);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1, 0L);
}
private final int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 79:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000000L, active1, 0L);
      case 100:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 36, 38);
         break;
      case 101:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(8, 18, 38);
         else if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 63, 38);
         return jjMoveStringLiteralDfa9_0(active0, 0x2000000000L, active1, 0L);
      case 104:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 61, 38);
         break;
      case 108:
         if ((active1 & 0x800000000000L) != 0L)
            return jjStopAtPos(8, 111);
         break;
      case 110:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 41, 38);
         break;
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000000L, active1, 0L);
      case 116:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(8, 22, 38);
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x200000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1, 0L);
}
private final int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(7, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, active1, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 78:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(9, 28, 74);
         break;
      case 100:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 37, 38);
         break;
      case 101:
         if ((active1 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(9, 85, 38);
         break;
      case 110:
         return jjMoveStringLiteralDfa10_0(active0, 0x80000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, active1, 0L);
}
private final int jjMoveStringLiteralDfa10_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(8, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, 0L, 0L);
      return 10;
   }
   switch(curChar)
   {
      case 115:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(10, 31, 38);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0, 0L, 0L);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 73;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 26:
               case 38:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAdd(38);
                  break;
               case 70:
               case 72:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 118)
                     kind = 118;
                  jjCheckNAdd(72);
                  break;
               case 73:
               case 58:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAdd(38);
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 123)
                        kind = 123;
                     jjCheckNAdd(38);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 115)
                        kind = 115;
                     jjCheckNAddTwoStates(5, 6);
                  }
                  break;
               case 16:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAdd(38);
                  break;
               case 3:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 112)
                        kind = 112;
                     jjCheckNAddStates(4, 12);
                  }
                  else if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(58, 4);
                  else if (curChar == 34)
                     jjCheckNAddStates(13, 15);
                  else if (curChar == 39)
                     jjCheckNAddStates(16, 18);
                  else if (curChar == 36)
                     jjstateSet[jjnewStateCnt++] = 9;
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 74:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 118)
                        kind = 118;
                     jjCheckNAdd(72);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 117)
                        kind = 117;
                     jjCheckNAdd(71);
                  }
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAdd(38);
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAdd(38);
                  break;
               case 0:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 1:
                  if ((0xffff7fffffffffffL & l) != 0L && kind > 7)
                     kind = 7;
                  break;
               case 2:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 115)
                     kind = 115;
                  jjCheckNAddTwoStates(5, 6);
                  break;
               case 6:
                  if (curChar == 46)
                     jjCheckNAdd(7);
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 115)
                     kind = 115;
                  jjCheckNAdd(7);
                  break;
               case 8:
                  if (curChar == 36)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 116)
                     kind = 116;
                  jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 119)
                     kind = 119;
                  jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 15:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 120)
                     kind = 120;
                  jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 121)
                     kind = 121;
                  jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 122)
                     kind = 122;
                  jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 39:
                  if (curChar == 39)
                     jjCheckNAddStates(16, 18);
                  break;
               case 40:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     jjCheckNAddStates(16, 18);
                  break;
               case 42:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAddStates(16, 18);
                  break;
               case 43:
                  if (curChar == 39 && kind > 126)
                     kind = 126;
                  break;
               case 44:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(19, 22);
                  break;
               case 45:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(16, 18);
                  break;
               case 46:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 47:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(45);
                  break;
               case 48:
                  if (curChar == 34)
                     jjCheckNAddStates(13, 15);
                  break;
               case 49:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(13, 15);
                  break;
               case 51:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAddStates(13, 15);
                  break;
               case 52:
                  if (curChar == 34 && kind > 127)
                     kind = 127;
                  break;
               case 53:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(23, 26);
                  break;
               case 54:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(13, 15);
                  break;
               case 55:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 56:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(54);
                  break;
               case 57:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(58, 4);
                  break;
               case 59:
                  if (curChar == 46)
                     jjCheckNAdd(60);
                  break;
               case 60:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(27, 29);
                  break;
               case 61:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(4);
                  break;
               case 62:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 112)
                     kind = 112;
                  jjCheckNAddStates(4, 12);
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 112)
                     kind = 112;
                  jjCheckNAdd(63);
                  break;
               case 64:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(64, 65);
                  break;
               case 66:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(66, 67);
                  break;
               case 67:
                  if (curChar == 46)
                     jjCheckNAdd(68);
                  break;
               case 68:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 114)
                     kind = 114;
                  jjCheckNAdd(68);
                  break;
               case 71:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 117)
                     kind = 117;
                  jjCheckNAdd(71);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 26:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 123)
                        kind = 123;
                     jjCheckNAdd(38);
                  }
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 70:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 118)
                        kind = 118;
                     jjCheckNAdd(72);
                  }
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 117)
                        kind = 117;
                     jjCheckNAdd(71);
                  }
                  break;
               case 73:
               case 4:
                  if (curChar != 105)
                     break;
                  if (kind > 115)
                     kind = 115;
                  jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 11:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 123)
                        kind = 123;
                     jjCheckNAdd(38);
                  }
                  if (curChar == 95)
                     jjCheckNAdd(12);
                  break;
               case 17:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 123)
                        kind = 123;
                     jjCheckNAdd(38);
                  }
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 16:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 123)
                        kind = 123;
                     jjCheckNAdd(38);
                  }
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 3:
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 118)
                        kind = 118;
                     jjCheckNAddTwoStates(70, 72);
                  }
                  else if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 123)
                        kind = 123;
                     jjCheckNAdd(38);
                  }
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 35;
                  else if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 26;
                  else if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 17;
                  else if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 11;
                  if (curChar == 105)
                  {
                     if (kind > 115)
                        kind = 115;
                     jjstateSet[jjnewStateCnt++] = 5;
                  }
                  break;
               case 74:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 118)
                        kind = 118;
                     jjCheckNAdd(72);
                  }
                  if ((0x87fffffeL & l) != 0L)
                  {
                     if (kind > 117)
                        kind = 117;
                     jjCheckNAdd(71);
                  }
                  break;
               case 14:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 123)
                        kind = 123;
                     jjCheckNAdd(38);
                  }
                  if (curChar == 95)
                     jjCheckNAdd(15);
                  break;
               case 35:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 123)
                        kind = 123;
                     jjCheckNAdd(38);
                  }
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 1:
                  if (kind > 7)
                     kind = 7;
                  break;
               case 9:
               case 10:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 116)
                     kind = 116;
                  jjCheckNAdd(10);
                  break;
               case 12:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 119)
                     kind = 119;
                  jjCheckNAdd(12);
                  break;
               case 13:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 15:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 120)
                     kind = 120;
                  jjCheckNAdd(15);
                  break;
               case 18:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
                  if (curChar == 95)
                     jjCheckNAdd(20);
                  break;
               case 20:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 121)
                     kind = 121;
                  jjCheckNAdd(20);
                  break;
               case 21:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 22:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 23:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 25:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 27:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if (curChar == 95)
                     jjCheckNAdd(29);
                  break;
               case 29:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 122)
                     kind = 122;
                  jjCheckNAdd(29);
                  break;
               case 30:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 31:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 33:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 34:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 36:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if ((0x7fffffe00000000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAdd(38);
                  break;
               case 38:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  jjCheckNAdd(38);
                  break;
               case 40:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(16, 18);
                  break;
               case 41:
                  if (curChar == 92)
                     jjAddStates(30, 32);
                  break;
               case 42:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(16, 18);
                  break;
               case 49:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(13, 15);
                  break;
               case 50:
                  if (curChar == 92)
                     jjAddStates(33, 35);
                  break;
               case 51:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(13, 15);
                  break;
               case 65:
                  if (curChar == 110 && kind > 113)
                     kind = 113;
                  break;
               case 69:
                  if ((0x7fffffeL & l) == 0L)
                     break;
                  if (kind > 118)
                     kind = 118;
                  jjCheckNAddTwoStates(70, 72);
                  break;
               case 71:
                  if ((0x87fffffeL & l) == 0L)
                     break;
                  if (kind > 117)
                     kind = 117;
                  jjCheckNAdd(71);
                  break;
               case 72:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 118)
                     kind = 118;
                  jjCheckNAdd(72);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) != 0L && kind > 7)
                     kind = 7;
                  break;
               case 40:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(16, 18);
                  break;
               case 49:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(13, 15);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 73 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private final int jjMoveStringLiteralDfa0_5()
{
   switch(curChar)
   {
      case 42:
         return jjMoveStringLiteralDfa1_5(0x800L);
      default :
         return 1;
   }
}
private final int jjMoveStringLiteralDfa1_5(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active0 & 0x800L) != 0L)
            return jjStopAtPos(1, 11);
         break;
      default :
         return 2;
   }
   return 2;
}
private final int jjMoveStringLiteralDfa0_3()
{
   return jjMoveNfa_3(0, 0);
}
private final int jjMoveNfa_3(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 3;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x2400L & l) != 0L)
                  {
                     if (kind > 9)
                        kind = 9;
                  }
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 1:
                  if (curChar == 10 && kind > 9)
                     kind = 9;
                  break;
               case 2:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 3 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private final int jjStopStringLiteralDfa_2(int pos, long active0)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private final int jjStartNfa_2(int pos, long active0)
{
   return jjMoveNfa_2(jjStopStringLiteralDfa_2(pos, active0), pos + 1);
}
private final int jjStartNfaWithStates_2(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_2(state, pos + 1);
}
private final int jjMoveStringLiteralDfa0_2()
{
   switch(curChar)
   {
      case 9:
         return jjStopAtPos(0, 2);
      case 10:
         return jjStopAtPos(0, 3);
      case 12:
         return jjStopAtPos(0, 5);
      case 13:
         return jjStopAtPos(0, 4);
      case 32:
         return jjStopAtPos(0, 1);
      default :
         return jjMoveNfa_2(0, 0);
   }
}
private final int jjMoveNfa_2(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 2;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0xc00000000000L & l) == 0L)
                     break;
                  if (kind > 129)
                     kind = 129;
                  jjCheckNAdd(1);
                  break;
               case 1:
                  if ((0x7ffc00000000000L & l) == 0L)
                     break;
                  if (kind > 129)
                     kind = 129;
                  jjCheckNAdd(1);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 1:
                  if ((0x7fffffe97fffffeL & l) == 0L)
                     break;
                  if (kind > 129)
                     kind = 129;
                  jjCheckNAdd(1);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 2 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private final int jjMoveStringLiteralDfa0_4()
{
   switch(curChar)
   {
      case 42:
         return jjMoveStringLiteralDfa1_4(0x400L);
      default :
         return 1;
   }
}
private final int jjMoveStringLiteralDfa1_4(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active0 & 0x400L) != 0L)
            return jjStopAtPos(1, 10);
         break;
      default :
         return 2;
   }
   return 2;
}
private final int jjStopStringLiteralDfa_1(int pos, long active0)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private final int jjStartNfa_1(int pos, long active0)
{
   return jjMoveNfa_1(jjStopStringLiteralDfa_1(pos, active0), pos + 1);
}
private final int jjStartNfaWithStates_1(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_1(state, pos + 1);
}
private final int jjMoveStringLiteralDfa0_1()
{
   switch(curChar)
   {
      case 9:
         return jjStopAtPos(0, 2);
      case 10:
         return jjStopAtPos(0, 3);
      case 12:
         return jjStopAtPos(0, 5);
      case 13:
         return jjStopAtPos(0, 4);
      case 32:
         return jjStopAtPos(0, 1);
      default :
         return jjMoveNfa_1(0, 0);
   }
}
private final int jjMoveNfa_1(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 2;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  kind = 128;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 1:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 128)
                     kind = 128;
                  jjCheckNAdd(1);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 2 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   58, 59, 61, 4, 63, 64, 65, 66, 67, 58, 59, 61, 4, 49, 50, 52, 
   40, 41, 43, 40, 41, 45, 43, 49, 50, 54, 52, 60, 61, 4, 42, 44, 
   46, 51, 53, 55, 
};
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
"\141\163\155", "\155\157\144\165\154\145", "\141\163\171\156\143\162", 
"\151\155\160\157\162\164", "\145\170\160\157\162\164", "\163\151\147\156\141\164\165\162\145", 
"\151\156\151\164", "\144\145\146\141\165\154\164", "\141\147\145\156\164", 
"\151\156\166\141\162\151\141\156\164", "\103\124\114\123\120\105\103", "\116\101\115\105", 
"\114\124\114\123\120\105\103", "\112\125\123\124\111\103\105", "\106\101\111\122\116\105\123\123", 
"\103\117\115\120\101\123\123\111\117\116", "\111\116\126\101\122", "\157\166\145\162", 
"\144\145\146\151\156\151\164\151\157\156\163", "\146\165\156\143\164\151\157\156", "\163\164\141\164\151\143", 
"\144\171\156\141\155\151\143", "\144\145\162\151\166\145\144", "\155\157\156\151\164\157\162\145\144", 
"\143\157\156\164\162\157\154\154\145\144", "\163\150\141\162\145\144", "\157\165\164", "\144\157\155\141\151\156", 
"\141\156\171\144\157\155\141\151\156", "\142\141\163\151\143", "\141\142\163\164\162\141\143\164", 
"\145\156\165\155", "\163\165\142\163\145\164\157\146", "\120\162\157\144", "\123\145\161", 
"\120\157\167\145\162\163\145\164", "\102\141\147", "\115\141\160", "\122\165\154\145", "\164\162\165\145", 
"\146\141\154\163\145", "\165\156\144\145\146", "\151", "\151\146", "\164\150\145\156", 
"\145\154\163\145", "\145\156\144\151\146", "\163\167\151\164\143\150", 
"\145\156\144\163\167\151\164\143\150", "\143\141\163\145", "\157\164\150\145\162\167\151\163\145", 
"\145\156\144\143\141\163\145", "\154\145\164", "\145\156\144\154\145\164", "\145\170\151\163\164", 
"\165\156\151\161\165\145", "\167\151\164\150", "\146\157\162\141\154\154", "\163\153\151\160", 
"\162\165\154\145", "\155\141\143\162\157", "\164\165\162\142\157", "\155\141\151\156", 
"\160\141\162", "\145\156\144\160\141\162", "\143\150\157\157\163\145", "\144\157", 
"\151\146\156\157\156\145", "\145\170\164\145\156\144", "\163\145\161", "\145\156\144\163\145\161", 
"\151\164\145\162\141\164\145", "\145\156\144\151\164\145\162\141\164\145", "\154\157\143\141\154", 
"\164\162\171", "\143\141\164\143\150", "\167\150\151\154\145", 
"\167\150\151\154\145\162\145\143", "\151\156", "\75", "\74", "\74\75", "\76", "\76\75", "\41\75", "\53", "\55", 
"\52", "\57", "\136", "\156\157\164\151\156", "\151\146\146", "\141\156\144", 
"\156\157\164", "\157\162", "\170\157\162", "\151\155\160\154\151\145\163", "\155\157\144", 
"\100\157\162\151\147\151\156\141\154", null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, "\50", "\54", "\51", "\72", "\173", "\174", "\175", 
"\55\76", "\56", "\56\56", "\133", "\135", "\74\74", "\76\76", "\43", "\72\75", 
"\74\55", };
public static final String[] lexStateNames = {
   "DEFAULT", 
   "GENERIC_ID", 
   "MODULE_ID", 
   "IN_SINGLE_LINE_COMMENT", 
   "IN_FORMAL_COMMENT", 
   "IN_MULTI_LINE_COMMENT", 
};
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, 3, 4, 5, 0, 0, 0, -1, 1, 1, -1, 2, -1, -1, 1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xffffffffffffe001L, 0xcfffffffffffffffL, 0x7ffffL, 
};
static final long[] jjtoSkip = {
   0xe3eL, 0x0L, 0x0L, 
};
static final long[] jjtoSpecial = {
   0xe3eL, 0x0L, 0x0L, 
};
static final long[] jjtoMore = {
   0x11c0L, 0x0L, 0x0L, 
};
protected CharStream input_stream;
private final int[] jjrounds = new int[73];
private final int[] jjstateSet = new int[146];
StringBuffer image;
int jjimageLen;
int lengthOfMatch;
protected char curChar;
public AsmetaLParserTokenManager(CharStream stream){
   input_stream = stream;
}
public AsmetaLParserTokenManager(CharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(CharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 73; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(CharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 6 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   t.offset = input_stream.getOffset();
   t.length = input_stream.getLength();
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }
   image = null;
   jjimageLen = 0;

   for (;;)
   {
     switch(curLexState)
     {
       case 0:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_0();
         break;
       case 1:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_1();
         break;
       case 2:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_2();
         break;
       case 3:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_3();
         if (jjmatchedPos == 0 && jjmatchedKind > 12)
         {
            jjmatchedKind = 12;
         }
         break;
       case 4:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_4();
         if (jjmatchedPos == 0 && jjmatchedKind > 12)
         {
            jjmatchedKind = 12;
         }
         break;
       case 5:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_5();
         if (jjmatchedPos == 0 && jjmatchedKind > 12)
         {
            jjmatchedKind = 12;
         }
         break;
     }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
           matchedToken.specialToken = specialToken;
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else if ((jjtoSkip[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
           {
              matchedToken = jjFillToken();
              if (specialToken == null)
                 specialToken = matchedToken;
              else
              {
                 matchedToken.specialToken = specialToken;
                 specialToken = (specialToken.next = matchedToken);
              }
              SkipLexicalActions(matchedToken);
           }
           else 
              SkipLexicalActions(null);
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
        MoreLexicalActions();
      if (jjnewLexState[jjmatchedKind] != -1)
        curLexState = jjnewLexState[jjmatchedKind];
        curPos = 0;
        jjmatchedKind = 0x7fffffff;
        try {
           curChar = input_stream.readChar();
           continue;
        }
        catch (java.io.IOException e1) { }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
   }
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      case 7 :
         if (image == null)
            image = new StringBuffer();
         image.append(input_stream.GetSuffix(jjimageLen));
         jjimageLen = 0;
                   input_stream.backup(1);
         break;
      default : 
         break;
   }
}
}
